//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoollaExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.customer = new HashSet<customer>();
        }
    
        public int uid { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<customer> customer { get; set; }
    }
}
